apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-ccfx
  namespace: octopus
  labels:
    app: octopus-ccfx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: octopus-ccfx
  template:
    metadata:
      labels:
        app: octopus-ccfx
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: octopus-ccfx
        image: registry.cn-shanghai.aliyuncs.com/k8shao/nginx:1.27-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
        volumeMounts:
        - name: octopus-logs
          mountPath: /tmp/octopus
      volumes:
      - name: octopus-logs
        emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: midas-acr
