apiVersion: v1
kind: Service
metadata:
  name: octopus-ccfx
  namespace: octopus
  labels:
    app: octopus-ccfx
spec:
  type: NodePort
  selector:
    app: octopus-ccfx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30800
    name: tcp
