apiVersion: v1
kind: Service
metadata:
  name: octopus-ccfx
  namespace: octopus
  labels:
    app: octopus-ccfx
spec:
  type: NodePort
  selector:
    app: octopus-ccfx
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    name: tcp
  - port: 20790
    targetPort: 20790
    nodePort: 30790
    name: socket
